### PR TITLE
Global announcements for op commands

### PR DESCRIPTION
**Pull request by mokus0**
Added broadcast messages for cheats and new config option to enable/disable them.

By default, they are enabled.

### CODE REVIEW

**Comment by EvilSeph** [comment]
Not sure what you're trying to achieve here...

**Comment by mokus0** [comment]
I'm not _trying_ to achieve anything.  I added a feature I wanted and was offering it back to the community.  Of course you're free to reject it but there's no need to be rude.

**Comment by EvilSeph** [comment]
I was not being rude. I genuinely did not and do not understand what you're trying to achieve and I was cleaning up the pull requests, so I closed it. My apologies if it came off as anything but my providing a reason for closing it, I did not intend to offend you.

**Comment by mokus0** [comment]
In that case, I apologize as well for my reaction.  The way it was phrased (and the fact that it didn't seem to be asking for any response, just dismissing it) gave me the wrong impression.

The point of this patch is to make it so that when any admin uses one of the commands, it announces that fact to everyone on the server.  For example, if I "/give DIAMOND_BLOCK 64", everyone can see that I've done so, or if i "/tphere foobar", foobar (and everyone else) knows who is dragging them around.

The reason for this is that on my server, almost all the users are people that I trust not to abuse ops, so I let most people have it.  At the same time, though, I don't want to encourage them to use things like /give so much that they ignore the server economy system.  So, I make them pay a social cost to use these commands - the slight embarrassment of knowing everyone else knows they are doing it.

The patch also introduces a config.yml file with an option that controls whether or not those announcements are made.

**Pull request closed without merging**
